export * from "@/pages/home";
export * from "@/pages/RecordPage";
export * from "@/pages/Contact";
export * from "@/pages/Feature";
export * from "@/pages/AboutPackage";
export * from "@/pages/PaymentPage";
export * from "@/pages/AppDemo";
export * from "@/pages/SignUp";
export * from "@/pages/SignIn";
